services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: viewwing-backend
    restart: unless-stopped
    env_file:
      - .env.production
    ports:
      - "3000:3000"
    volumes:
      - ./logs:/app/logs
    networks:
      - default
      - panel

networks:
  panel:
    external: true
    name: 1panel-network
